osx_image: xcode11.6
language: swift
os: osx
xcode_project: CurrentWeather.xcodeproj
xcode_scheme: CurrentWeatherTests
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
before_install:
  pod install
